---
driver:
  name: ec2
  aws_ssh_key_id: devopskey
  region: us-east-1
  availability_zone: a
  subnet_id: subnet-e0a4c785
  instance_type: t2.micro
  image_id: ami-b63769a1
  security_group_ids: sg-d2c8a2ad
  retryable_tries: 120

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

transport:
  ssh_key: /root/.ssh/devopskey.pem

platforms:
#  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[webserver_test::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
